.TH "TimeSeries< T >::iterator" 3 "Sun Jan 5 2020" "Version 1.0" "Akamai Analyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimeSeries< T >::iterator
.SH SYNOPSIS
.br
.PP
.PP
Inherits iterator< std::input_iterator_tag, TimeSeries< T >::timeslot, int, TimeSeries< T >::timeslot *, TimeSeries< T >::timeslot >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBiterator\fP (\fBTimeSeries\fP< T > *p, double _timepoint=0)"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBiterator\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBiterator\fP other) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBiterator\fP other) const"
.br
.ti -1c
.RI "iterator_traits< \fBiterator\fP >::reference \fBoperator *\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Akamai Analyzer from the source code\&.
