.TH "TimeSeries< T >::timeslot" 3 "Sun Jan 5 2020" "Version 1.0" "Akamai Analyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimeSeries< T >::timeslot
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBbegin_time\fP"
.br
.ti -1c
.RI "double \fBend_time\fP"
.br
.ti -1c
.RI "multimap< double, T > * \fBdatapoints\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Akamai Analyzer from the source code\&.
