.TH "Tx" 3 "Sun Jan 5 2020" "Version 1.0" "Akamai Analyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tx
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTx\fP (vector< string > vs)"
.br
.ti -1c
.RI "bool \fBhasValidThroughput\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcontent_size\fP"
.br
.ti -1c
.RI "int \fBtotal_size\fP"
.br
.ti -1c
.RI "int \fBtransfer_time\fP"
.br
.ti -1c
.RI "int \fBssl_time\fP"
.br
.ti -1c
.RI "int \fBreq_end_time\fP"
.br
.ti -1c
.RI "int \fBturnaround_time\fP"
.br
.ti -1c
.RI "string \fBstatus_code\fP"
.br
.ti -1c
.RI "string \fBerror_code\fP"
.br
.ti -1c
.RI "string \fBflag\fP"
.br
.ti -1c
.RI "double \fBtimestamp\fP"
.br
.ti -1c
.RI "string \fBreq_id\fP"
.br
.ti -1c
.RI "string \fBarl\fP"
.br
.ti -1c
.RI "string \fBbyte_range\fP"
.br
.ti -1c
.RI "string \fBghost_ip\fP"
.br
.ti -1c
.RI "string \fBclient_ip\fP"
.br
.ti -1c
.RI "float \fBthroughput\fP"
.br
.ti -1c
.RI "int \fBtotal_time\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Akamai Analyzer from the source code\&.
